### ISSUE TITLE
Is this actively supported?

### ISSUE THREAD

**Issue by ajtruckle** [stanthomas/tinyxml2-ex#5]
I see the last commits were over 5 years ago.

**Comment by stanthomas** [comment]
And your point is?

**Comment by ajtruckle** [comment]
I am aware of  a few updates to tinyxml 2 within the last few years. Perhaps a note stating the version of tinyxml2 it has been officially tested with?

Wish I had this library before! 👍

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stanthomas** [comment]
Ok. I'm not aware of any changes to tinyxml2 that affect the public interface, or at least the parts of the public interface used  by tinyxml2-ex. But thank you for raising the question and I will look to see whether there are any compatiblity issues with the lastest tinyxml2

**Comment by ajtruckle** [comment]
At the moment it seems to be working fine for me! Thanks for the API library! I am just ironing out some bits of code logic (separate issue tickets for them).
